### ISSUE TITLE
Re-add Beerware License

### ISSUE THREAD

**Issue by theycallmeswift** [getstrike/node-db-s3-backup#6]
Hey folks --

Looking at the commit history and codebase, it appears that this is actually a fork of [node-mongodb-s3-backup](https://github.com/theycallmeswift/node-mongodb-s3-backup).  Looks like you've added a bunch of new features, which is awesome!

Unfortunately, it looks like you accidentally removed all of the license and author information.  As you can see if you look back at the `package.json` (https://github.com/getstrike/node-db-s3-backup/blob/2b46e3d342d925cd686d1a454e0b01e1d4dbf2a1/package.json), this library was released under the Beerware license which means that you actually need to retain the license to credit my original work.  

I'd be happy with you adding the following `LICENSE` file back in or restoring the details from the `package.json`.

```
/*
 * ----------------------------------------------------------------------------
 * "THE BEER-WARE LICENSE" (Revision 42):
 * <theycallmeswift@gmail.com> wrote this file.  As long as you retain this notice you
 * can do whatever you want with this stuff. If we meet some day, and you think
 * this stuff is worth it, you can buy me a beer in return.   Mike Swift
 * ----------------------------------------------------------------------------
 */
```

Let me know if you have any questions. Happy hacking!

\- Swift

**Comment by MrDHat** [comment]
Hey @theycallmeswift thanks for pointing it out!

This might have been an oversight. So sorry for that. Adding the license again :)

**Comment by theycallmeswift** [comment]
@MrDHat great, thanks!  FYI looks like you accidentally forgot to update the License in the README.

**Comment by MrDHat** [comment]
Whoops! Added now.
